print ('Student-1 details')
# print ("Student Name: ", student1.name)
# print ('Age :', student1.age)
# print ('Id: ', student1.id)        
# print()
# print ('Student-2 details')
# print ("Student Name: ", student2.name)
# print ('Age :', student2.age)
# print ('Id: ', student2.id)